version: '2'

networks:
  proxy:

volumes:
  nginx_config:
 
services:
  nginx:
    image: nginx
    container_name: proxy-nginx
    networks:
      - proxy
    ports:
      - '80:80'
    volumes:
      - nginx_config:/etc/nginx

  docker_gen:
    image: jwilder/docker-gen
    command:
      - '-notify'
      - 'docker kill -s HUP proxy-nginx'
      - '-watch'
      - '-only-exposed'
      - '/etc/docker-gen/templates/nginx.tmpl'
      - '/etc/nginx/conf.d/default.conf'
    container_name: proxy-gen
    environment:
      DOCKER_HOST: tcp://10.1.0.10:4000
    networks:
      - proxy
    volumes:
      - nginx_config:/etc/nginx
    volumes_from:
      - docker_gen_config

  docker_gen_config:
    build: docker-gen-config
    container_name: proxy-gen-config
    networks:
      - proxy
