version: '2'

networks:
  proxy:
    driver: overlay
  web:
    driver: overlay

volumes:
  nginx_config:
 
services:
  nginx:
    image: nginx
    container_name: proxy-nginx
    environment:
      'constraint:node==nginx-lb-0':
    networks:
      - proxy
    ports:
      - '80:80'
    volumes:
      - nginx_config:/etc/nginx

  docker_gen:
    image: jwilder/docker-gen
    command:
      - '-notify-sighup'
      - 'proxy-nginx'
      - '-watch'
      - '-only-exposed'
      - '/etc/docker-gen/templates/nginx.tmpl'
      - '/etc/nginx/conf.d/default.conf'
    container_name: proxy-gen
    environment:
      DOCKER_HOST: tcp://10.1.0.10:4000
      'constraint:node==nginx-lb-0':
    networks:
      - proxy
    volumes:
      - nginx_config:/etc/nginx
    volumes_from:
      - docker_gen_config

  docker_gen_config:
    build:
      context: docker-gen-config
      args:
        - 'constraint:node==nginx-lb-0'
    container_name: proxy-gen-config
    image: proxy-gen-config
    environment:
      'constraint:node==nginx-lb-0':
    networks:
      - proxy
  
  web_app:
    image: nginx
    environment:
      VIRTUAL_HOST: webapp.mistersg.net
      VIRTUAL_PORT: '80'
    networks:
      - web
      - proxy
    ports:
      - '80'
    restart: 'no'
